# Generated by Django 5.2.9 on 2026-01-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(help_text="e.g., '30+', '$2B+', '98%'", max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Achievement Metric',
                'verbose_name_plural': 'Achievement Metrics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('matter_type', models.CharField(choices=[('corporate', 'Corporate & Commercial'), ('litigation', 'Commercial Litigation'), ('tax', 'Tax Advisory'), ('real-estate', 'Real Estate & Property'), ('employment', 'Employment Law'), ('intellectual', 'Intellectual Property'), ('regulatory', 'Regulatory Compliance'), ('other', 'Other')], max_length=50)),
                ('urgency', models.CharField(choices=[('standard', 'Standard (1-2 weeks)'), ('priority', 'Priority (3-5 days)'), ('urgent', 'Urgent (24-48 hours)')], default='standard', max_length=20)),
                ('details', models.TextField()),
                ('referral_source', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('contacted', 'Client Contacted')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Professional Recognition',
                'verbose_name_plural': 'Professional Recognition',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(help_text="e.g., 'CEO, Leading Financial Institution'", max_length=255)),
                ('role', models.CharField(help_text='Matter type or industry', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client Testimonial',
                'verbose_name_plural': 'Client Testimonials',
                'ordering': ['order'],
            },
        ),
    ]
